################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.c \
../Core/Inc/dsdlc_generated/src/uavcan.Timestamp.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Mode.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.c 

C_DEPS += \
./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.d \
./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Mode.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.d 

OBJS += \
./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.o \
./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Mode.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.o 


# Each subdirectory must supply rules for building sources it contributes
Core/Inc/dsdlc_generated/src/%.o Core/Inc/dsdlc_generated/src/%.su Core/Inc/dsdlc_generated/src/%.cyclo: ../Core/Inc/dsdlc_generated/src/%.c Core/Inc/dsdlc_generated/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L552xx -c -I../Core/Inc -I../Drivers/STM32L5xx_HAL_Driver/Inc -I../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure -I../FATFS/Target -I../FATFS/App -I../Middlewares/Third_Party/FatFs/src -I"C:/Users/ronak/OneDrive - University of Waterloo/Desktop/Ronak__Backup_2025_11_07/Files/Warg/efs-zeropilot-3.5b/stm32l552xx/boardfiles/drivers/rfd" -I../boardfiles/drivers/logger -I../boardfiles/utils -I../Core/Inc/dsdlc_generated/include -I../boardfiles/drivers/can -I../boardfiles/drivers/gps -I../boardfiles/drivers/iwdg -I../boardfiles/drivers/motor -I../boardfiles/drivers/rc -I../boardfiles/drivers/rfd -I../boardfiles/model/inc -I../boardfiles/rtos/museq -I../boardfiles/rtos/threads/inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-Inc-2f-dsdlc_generated-2f-src

clean-Core-2f-Inc-2f-dsdlc_generated-2f-src:
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.d ./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.o ./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.su ./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.d ./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.o ./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Mode.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Mode.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Mode.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Mode.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Status.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.camera_gimbal.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.su
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.su
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.d ./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.o ./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.su
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.cyclo
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.su

.PHONY: clean-Core-2f-Inc-2f-dsdlc_generated-2f-src

