name: ZP4 Lib Compile Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile_test_plane:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Restore Docker image cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: efs-zeropilot-ci-v1.0.0-{hash}
        restore-keys: |
          efs-zeropilot-ci-v1.0.0-

    - name: Build project
      run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/zeropilot4.0 uwarg/efs-zeropilot-ci:v1.0.0 bash ./hwbuild.bash -c -v plane -b l552

  compile_test_quad:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Restore Docker image cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: efs-zeropilot-ci-v1.0.0-{hash}
        restore-keys: |
          efs-zeropilot-ci-v1.0.0-

    - name: Build project
      run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/zeropilot4.0 uwarg/efs-zeropilot-ci:v1.0.0 bash ./hwbuild.bash -c -v quad -b l552
