name: ZP4 Lib Compile Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile_test_plane:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Cache Docker image
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: /tmp/efs-zeropilot-ci-v1.0.0.tar
        key: efs-zeropilot-ci-v1.0.0-${{ runner.os }}

    - name: Load or pull Docker image
      run: |
        if [[ -f /tmp/efs-zeropilot-ci-v1.0.0.tar ]]; then
          docker load --input /tmp/efs-zeropilot-ci-v1.0.0.tar
        else
          docker pull uwarg/efs-zeropilot-ci:v1.0.0
          docker save --output /tmp/efs-zeropilot-ci-v1.0.0.tar uwarg/efs-zeropilot-ci:v1.0.0
        fi

    - name: Build project
      run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/zeropilot4.0 uwarg/efs-zeropilot-ci:v1.0.0 bash ./hwbuild.bash -c -v plane -b l552

  compile_test_quad:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Cache Docker image
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: /tmp/efs-zeropilot-ci-v1.0.0.tar
        key: efs-zeropilot-ci-v1.0.0-${{ runner.os }}

    - name: Load or pull Docker image
      run: |
        if [[ -f /tmp/efs-zeropilot-ci-v1.0.0.tar ]]; then
          docker load --input /tmp/efs-zeropilot-ci-v1.0.0.tar
        else
          docker pull uwarg/efs-zeropilot-ci:v1.0.0
          docker save --output /tmp/efs-zeropilot-ci-v1.0.0.tar uwarg/efs-zeropilot-ci:v1.0.0
        fi

    - name: Build project
      run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/zeropilot4.0 uwarg/efs-zeropilot-ci:v1.0.0 bash ./hwbuild.bash -c -v quad -b l552
