name: Linting Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linting_test_plane:
    runs-on: ubuntu-latest
    container:
      image: uwarg/efs-zeropilot-ci:v1.0.0

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build main 
      working-directory: ./zeropilot4.0
      run: |
        bash ./hwbuild.bash -c l552 -v plane
        # Assuming hwbuild.bash configures CMake with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build tests
      working-directory: ./zeropilot4.0/tests
      run: |
        bash ./testbuild.bash -c -v plane
        # Same assumption for testbuild.bash

    - name: Run clang-tidy lint script
      working-directory: ./zeropilot4.0
      run: bash ./lint.bash -v plane

  linting_test_quad:
    runs-on: ubuntu-latest
    container:
      image: uwarg/efs-zeropilot-ci:v1.0.0

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build main 
      working-directory: ./zeropilot4.0
      run: |
        bash ./hwbuild.bash -c -v quad -b l552 
        # Assuming hwbuild.bash configures CMake with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build tests
      working-directory: ./zeropilot4.0/tests
      run: |
        bash ./testbuild.bash -c -v quad
        # Same assumption for testbuild.bash

    - name: Run clang-tidy lint script
      working-directory: ./zeropilot4.0
      run: bash ./lint.bash -v quad
