name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_test_plane:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Restore Docker image cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: efs-zeropilot-ci-v1.0.0-{hash}
        restore-keys: |
          efs-zeropilot-ci-v1.0.0-

    - name: Build tests
      run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/zeropilot4.0/tests uwarg/efs-zeropilot-ci:v1.0.0 bash ./testbuild.bash -c -v plane
    
    - name: Run tests
      run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/zeropilot4.0/tests uwarg/efs-zeropilot-ci:v1.0.0 bash -lc 'chmod +x build/gtestzeropilot4.0 && ./build/gtestzeropilot4.0'

  unit_test_quad:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Restore Docker image cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: efs-zeropilot-ci-v1.0.0-{hash}
        restore-keys: |
          efs-zeropilot-ci-v1.0.0-

    - name: Build tests
      run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/zeropilot4.0/tests uwarg/efs-zeropilot-ci:v1.0.0 bash ./testbuild.bash -c -v quad
    
    - name: Run tests
      run: docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/zeropilot4.0/tests uwarg/efs-zeropilot-ci:v1.0.0 bash -lc 'chmod +x build/gtestzeropilot4.0 && ./build/gtestzeropilot4.0'
